### ISSUE TITLE
Booking system: Backglass Replacement for iPhone 8-11PROMAX 

### ISSUE THREAD

**Issue by elbertcodes** [GelatoTech/www#14]
iPhone 8 $140
iPhone 8+ $140
iPhone X $150
iPhone XR $150
iPhone XS $150
iPhone XSMAX $150
iPhone 11 $180
iPhone 11PRO $180
iPhone 11 PROMAX $180

*** Make sure this problem only shows for iPhone 8-11PROMAX. Make sure it hides when you choose iPhone 6-7PLUS ***

**Comment by ikejs** [comment]
https://github.com/GelatoTech/www/commit/bc8020659cd12a4c81a62e1c26fdf3d3db0c6b8b
