### ISSUE TITLE
Booking system: iPad Warranty is 90 days for screen, battery, charging port replacement 

### ISSUE THREAD

**Issue by elbertcodes** [GelatoTech/www#15]
Please change the warranty for all iPads. 

It's currently "Lifetime warranty" 

Change it to "90 day warranty" for all repairs (screen, battery, charging port replacement )

**Comment by ikejs** [comment]
https://github.com/GelatoTech/www/commit/27b835cc2ea7f03544dd99180df758eff3267d6b
