### ISSUE TITLE
Google Pixel Screen, Battery, Charging Replacement 

### ISSUE THREAD

**Issue by elbertcodes** [GelatoTech/www#17]
Screen Replacement 

Google Pixel - $100
Google Pixel XL -$140
Google Pixel 2  - $130 
Google Pixel 2XL - $220 
Google Pixel 3 - $250
Google Pixel 3 XL - $280 
Google Pixel 3A - $200
Google pixel 4 - $200
Google Pixe 4xl - $280

Battery & Charging port replacement 

Google Pixel - $55
Google Pixel XL -$55
Google Pixel 2  - $55
Google Pixel 2XL - $55
Google Pixel 3 - $55
Google Pixel 3 XL - $55
Google Pixel 3A - $55
Google pixel 4 - $65
Google Pixe 4xl - $75
mailto:elbert@gelatotech.com

**Comment by ikejs** [comment]
https://github.com/GelatoTech/www/commit/ad84039a67b9523c24d52ff0ddf968e4dcc54c06
